version: "3.7"
services:
  discord-relay:
    image: vanilla-partnership/discord-relay
    restart: always
    volumes:
      - ./discord-relay.properties:/usr/relay/discord-relay.properties
    init: true
    container_name: discord-relay
    ports:
      - 601
    networks:
      relay:
        aliases:
          - discord-relay

  minecraft-server:
    image: templexmc/minecraft-server
    restart: always
    volumes:
      - data:/data
    ports:
      - 25565:25565
      - 25575
    env_file: minecraft.env
    init: true
    container_name: templex-server
    depends_on:
      - discord-relay
    links:
      - discord-relay
    networks:
      relay:
        aliases:
          - minecraft-server

  vanilla-votifier:
    image: templexmc/vanilla-votifier
    restart: always
    volumes:
      - ./votifier-config.yaml:/usr/votifier/config.yaml
    stdin_open: true
    ports:
      - 5723:5723
    init: true
    links:
      - "minecraft-server"
    container_name: vanilla-votifier
    depends_on:
      - minecraft-server

volumes:
  data: {}

networks:
  relay:
