version: "3.7"
services:
  minecraft-server:
    image: templexmc/game-wrapper-bot
    restart: always
    volumes:
      - data:/data
      - ./oklahomabot.properties:/data/oklahomabot.properties
    ports:
      - 25565:25565
      - 25575
    env_file: minecraft.env
    init: true
    container_name: templex-server

  vanilla-votifier:
    image: templexmc/vanilla-votifier
    restart: always
    volumes:
      - ./votifier-config.yaml:/usr/votifier/config.yaml
    stdin_open: true
    ports:
      - 5723:5723
    init: true
    links:
      - "minecraft-server"
    container_name: vanilla-votifier
    depends_on:
      - minecraft-server

volumes:
  data: {}
